# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8f0134f673d650f525ba183390568a47c2c06f28466e38dd1da61b9147fd147662579fc0395fe41f5fa006196dccf9c7b4467adcd75973cca8dd4a1d0073a4e

test:
  secret_key_base: 42410926824bb54ecb74125bdbdc8014a7eabe8dc2989363e934e9ae3474b0708d00930ca32c7b257ce0206646bf63856ac48a755e3fb7358ff127b38b8f4d8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
